title:            Joseph's Blog
description:      "Le livre est l'ami de la solitude et moi."
#to enaable disqus comments, add your username
disqus_shortname:  jinntrance
#to enaable duoshuo comments, add your username here
duoshuo_shortname: 
reading_time:     true
words_per_minute: 200
chars_per_minute: 600
abstract_chars_num: 220  
# When testing locally leave blank or use http://localhost:4000
#url: http://www.josephjctang.com/blog
domain: http://www.josephjctang.com
url: /blog/
baseurl: /blog/
apex_domain: josephjctang.com

# Owner/author information
owner:
  name:           Joseph
  avatar:         avatar70.jpg
  bio:            "Le livre est l'ami de la solitude et moi."
  email:          jinntrance@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        
  facebook:       
  github: jinntrance        
  stackexchange:  
  linkedin: josephjinchuantang     
  instagram:      
  flickr:         
  tumblr:         
  # google plus id, include the '+', eg +mmistakes
  google_plus: +JosephJinChuanTáng
  weibo: jinntrance
  douban: jinntrance
  weibo_name: "癡人憐我半瘋癲"
index_fullpost: false
# disable duoshuo share by default  
duoshuo_share: false  

# Background image to be tiled on all pages
background: 

# enable mathjax by default
mathjax: true
# if set true, mathjax will be loaded 
# only when there are elements with class `mathjax_alt`
mathjax_with_alt: true
# when mathjax fails, display those alternative elements
mathjax_alt_class: mathjax_alt

# load external scripts
jquery_lastest: false
mathjax_latest: false

# Analytics and webmaster tools stuff goes here
# can not access google service in China,
# Google Analytics ID
google_analytics: "UA-39438576-1"
google_verify:     
google_fonts: 
# add Baidu Analytics ID for tracking
baidu_analytics: 11224c4b3c0923fa6de6e431325fe387

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify: 
#

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Beijing
future:      true
#highlighter: pygments
markdown:    kramdown
gems:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from

sass:
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:year/:month/:title/

# Amount of post to show on home page
paginate: 5

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true
  input: GFM
  syntax_highlighter: rouge
  #syntax_highlighter: coderay

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 2
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
