title:            Joseph's Blog
description:      "Live more seriously within."
disqus_shortname: 
reading_time:     true
words_per_minute: 200
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
#url: http://www.josephjctang.com/
url: /blog
baseurl: /blog

# Owner/author information
owner:
  name:           Joseph
  avatar:         avatar70.jpg
  bio:            "Live more seriously within."
  email:          jinntrance@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        
  facebook:       
  github: jinntrance        
  stackexchange:  
  linkedin: josephjinchuantang     
  instagram:      
  flickr:         
  tumblr:         
  # google plus id, include the '+', eg +mmistakes
  google_plus: +JosephJinChuanTáng

# Background image to be tiled on all pages
background: 

#enable mathjax by default
mathjax: true

# load external scripts
jquery_lastest: 
mathjax_latest: true

# Analytics and webmaster tools stuff goes here
google_analytics:   
google_verify:     
google_fonts: 
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify: 
#
baidu_analytics:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Beijing
future:      true
highlighter: pygments
markdown:    kramdown
gems:
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:year/:month/:title/

# Amount of post to show on home page
paginate: 5

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 2
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
